networks:
  observability:
    name: observability
    driver: bridge

services:
  grafana:
    image: grafana/grafana:13.2.1
    networks: [ observability ]
    ports: [ "127.0.0.1:3000:3000" ]
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:3.7.7
    networks: [ observability ]
    ports: [ "127.0.0.1:3101:3100" ]
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yml:/etc/loki/config.yml

  prometheus:
    image: prom/prometheus:latest
    networks: [ observability ]
    ports: [ "127.0.0.1:9090:9090" ]
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  alloy:
    image: grafana/alloy:1.19.2
    container_name: alloy
    networks: [ observability ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log/nginx:/var/log/nginx:ro
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "127.0.0.1:12345:12345"

volumes:
  grafana-data:
  loki-data:
  prometheus-data:
  alloy-data:
