networks:
  observability:
    name: observability
    driver: bridge

services:
  grafana:
    image: grafana/grafana:13.2.1
    networks: [ observability ]
    ports: [ "127.0.0.1:3000:3000" ]
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:3.7.7
    networks: [ observability ]
    ports: [ "127.0.0.1:3101:3100" ]
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yml:/etc/loki/config.yml

  prometheus:
    image: prom/prometheus:latest
    networks: [ observability ]
    ports: [ "127.0.0.1:9090:9090" ]
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:v1.12.1
    container_name: node-exporter
    networks: [ observability ]
    ports: [ "127.0.0.1:9100:9100" ]
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    networks: [ observability ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log/nginx:/var/log/nginx:ro
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "127.0.0.1:12345:12345"

volumes:
  grafana-data:
  loki-data:
  prometheus-data:
  alloy-data:
