global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:

  - job_name: 'einsatzlog112-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['einsatzlog112-backend:8080']
        labels:
          app: einsatzlog112
          component: backend

  - job_name: 'monitor-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['monitor-backend:8080']
        labels:
          app: monitor
          component: backend
